#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias m="man"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"

command -v "xclip" &>/dev/null && {
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
}

alias +x="chmod +x"
alias z="zoxide"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# 'ls' aliases

command -v "exa" &>/dev/null && {
    alias ls="exa"

    # List all files colorized in long format
    alias l="exa -l"
}

# List only directories
alias lsd="ls -lF --color | grep --color=never '^d'"
# List only hidden files
alias lsh="ls -ld .?*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias lip="ipconfig getifaddr en0"

# Get external IP.

alias xip="curl -s checkip.dyndns.org | grep -Eo "\[0-9\.]+""

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Better `rm`

# Option 1: `rip` - a safer and more user-friendly alternative to 'rm'
# see: https://github.com/nivekuil/rip

if command -v rip &>/dev/null; then
    alias rm="rip"
fi

# Option 2: `trash` - safer alternative to 'rm'
# see: https://github.com/andreafrancia/trash-cli

if command -v trash &>/dev/null; then
    alias rm="trash"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `git` aliases

command -v "hub" &>/dev/null && {
    alias git=hub
}

alias acp="git add -A && git commit -v && git push"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `lazygit` aliases

command -v "lazygit" &>/dev/null && {
    alias lg="lazygit"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `wttr` alias

alias wttr="curl wttr.in"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# thefuck - Magnificent app which corrects your previous console command.
# see: https://github.com/nvbn/thefuck/wiki/Shell-aliases#bash
command -v thefuck &>/dev/null && {
    eval "$(thefuck --alias)"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Node Package Manager`

# alias n="npm" # Do not use if using 'n' for Node version control
command -v "npm" &>/dev/null && {
    alias npmi='npm i -g'
    alias npmr='npm uninstall -g'
    alias npmls='npm list -g --depth 0'
    alias npms='npm s'
    alias npmu='npm i -g npm@latest'
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Yarn Package Manager`

command -v "yarn" &>/dev/null && {
    alias yr='yarn remove'
    alias ya='yarn add'
    alias yu='yarn self-update && yarn upgrade && yarn upgrade-interactive'
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for `Homebrew`.

if command -v brew &>/dev/null; then
    alias brewd='brew doctor'
    alias brewi='brew install'
    alias brewr='brew uninstall'
    alias brews='brew search'

    # Function for updating and upgrading brew
    brewu() {
        brew upgrade
        brew cleanup

        if [ "$(uname)" = "Darwin" ]; then
            brew cask upgrade

            if command -v mas &>/dev/null; then
                # Update Mac App Store apps
                mas upgrade
            fi
        fi
    }
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `pip`

command -v "pip" &>/dev/null && {
    alias pipi='pip install'
    alias pipr='pip uninstall'
    alias pipls='pip list'
    alias pips='pip search'
    alias pipu="sudo pip install --upgrade pip \
                    && sudo pip install --upgrade setuptools \
                    && sudo pip-review --auto"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `pip3`

command -v "pip3" &>/dev/null && {
    alias pip3i='pip3 install'
    alias pip3r='pip3 uninstall'
    alias pip3ls='pip3 list'
    alias pip3s='pip3 search'
    alias pip3u="sudo pip3 install -U pip \
                    && sudo -H pip3 install -U pip \
                    && sudo pip-review --auto"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for `Composer`

command -v "composer" &>/dev/null && {
    alias ci='composer install'
    alias cr='composer remove'
    alias cls='composer list'
    alias cs='composer search'
    alias cu='composer self-update'
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# piknik - Copy/paste anything over the network!
# see: https://github.com/jedisct1/piknik#suggested-shell-aliases

command -v "piknick" &>/dev/null && {
    # pkc : read the content to copy to the clipboard from STDIN
    alias pkc='piknik -copy'

    # pkp : paste the clipboard content
    alias pkp='piknik -paste'

    # pkm : move the clipboard content
    alias pkm='piknik -move'

    # pkz : delete the clipboard content
    alias pkz='piknik -copy < /dev/null'

    # pkpr : extract clipboard content sent using the pkfr command
    alias pkpr='piknik -paste | tar xzhpvf -'
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# has - checks presence of various command line tools and their versions on the path
# see: https://github.com/kdabir/has#running-directly-off-the-internet

alias has="curl -sL https://git.io/_has | bash -s"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# 'fzy' aliases

command -v "fzy" &>/dev/null && {
    alias fzyf="find . -type f | fzy"
    alias fzyd="find . -type d | fzy"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Lock screen.

# Check operating system type
case "$(uname)" in
Darwin)
    # MacOS alias
    alias afk='/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend'
    ;;

Linux)
    # Check for gnome-screensaver-command
    if command -v gnome-screensaver-command &>/dev/null; then
        alias afk='gnome-screensaver-command -l'
    # Check for dm-tool
    elif command -v dm-tool &>/dev/null; then
        alias afk='dm-tool lock'
    fi
    ;;
esac

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Hide/Show desktop icons.

# Hide desktop icons
case "$(uname)" in
Darwin)
    alias hide-desktop-icons='defaults write com.apple.finder CreateDesktop -bool false; killall Finder'
    ;;

Linux)
    # For GNOME
    alias hide-desktop-icons='gsettings set org.gnome.desktop.background show-desktop-icons false'
    ;;
esac

# Show desktop icons
case "$(uname)" in
Darwin)
    alias show-desktop-icons='defaults write com.apple.finder CreateDesktop -bool true; killall Finder'
    ;;

Linux)
    # For GNOME
    alias show-desktop-icons='gsettings set org.gnome.desktop.background show-desktop-icons true'
    ;;
esac

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# update CLTs

command -v "fish" &>/dev/null && [ -f "$HOME/.config/fish/functions/update.fish" ] && {
    alias update="fish -c \"update\""
}
